import './index.css';

import { Suspense } from 'react';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import Script from 'next/script';

import { AuthProvider } from '@/context/AuthContext';
import TanstackQueryProvider from '@/providers/QueryProvider';
import { Toaster } from '@/ui/sonner';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Edgebet',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="!scroll-smooth" suppressHydrationWarning>
      <head>
        <Script
          src="https://accounts.google.com/gsi/client"
          strategy="beforeInteractive"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} relative overflow-x-hidden antialiased`}
        suppressHydrationWarning
      >
        <Suspense fallback={<div>Loading...</div>}>
          <TanstackQueryProvider>
            <AuthProvider>
              <div>{children}</div>
              <Toaster />
            </AuthProvider>
          </TanstackQueryProvider>
        </Suspense>
      </body>
    </html>
  );
}
